INSERT INTO song (title, artist, album, genre) VALUES
('Midnight City', 'M83', 'Hurry Up, We''re Dreaming', 'Synth-pop'),
('Starboy', 'The Weeknd', 'Starboy', 'R&B'),
('Blinding Lights', 'The Weeknd', 'After Hours', 'Synth-pop'),
('HUMBLE.', 'Kendrick Lamar', 'DAMN.', 'Hip-Hop'),
('Alright', 'Kendrick Lamar', 'To Pimp a Butterfly', 'Hip-Hop'),
('Redbone', 'Childish Gambino', 'Awaken, My Love!', 'Funk'),
('Feel Good Inc.', 'Gorillaz', 'Demon Days', 'Alternative'),
('Clint Eastwood', 'Gorillaz', 'Gorillaz', 'Alternative'),
('Superstition', 'Stevie Wonder', 'Talking Book', 'Funk'),
('Get Lucky', 'Daft Punk', 'Random Access Memories', 'Funk'),
('One More Time', 'Daft Punk', 'Discovery', 'Electronic'),
('Strobe', 'Deadmau5', 'For Lack of a Better Name', 'Electronic'),
('Take Five', 'Dave Brubeck', 'Time Out', 'Jazz'),
('So What', 'Miles Davis', 'Kind of Blue', 'Jazz'),
('Come As You Are', 'Nirvana', 'Nevermind', 'Rock'),
('Everlong', 'Foo Fighters', 'The Colour and the Shape', 'Rock'),
('Bohemian Rhapsody', 'Queen', 'A Night at the Opera', 'Rock'),
('Circles', 'Post Malone', 'Hollywood''s Bleeding', 'Pop'),
('Levitating', 'Dua Lipa', 'Future Nostalgia', 'Pop'),
('Don''t Start Now', 'Dua Lipa', 'Future Nostalgia', 'Pop');